FROM golang:1.20-rc-buster AS srv-dependencies

WORKDIR /app

ENV GOPATH=/

COPY ././go.mod go.sum ./

RUN go mod download

FROM srv-dependencies AS build

WORKDIR /app

COPY ./././ .

RUN go build -o main ./cmd/main.go

FROM ubuntu:jammy

COPY --from=build ./app/main .
COPY --from=build ./app/wait-for-it.sh ./wait-for-it.sh
COPY --from=build ./app/configs/config.dev.json ./configs/config.json

CMD ["./wait-for-it.sh", "wakadoo_postgres:5432", "-t", "6", "--", "/app/main"]

EXPOSE 8080
